In [1]:
import pandas as pd
import numpy as np
from tqdm import tqdm
tqdm.pandas()

/mnt/datadisk2/aglv/anaconda3/lib/python3.8/site-packages/tqdm/std.py:668: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  from pandas import Panel

In [2]:
demo = pd.read_hdf('/mnt/datadisk2/aglv/aglv/lab_aglv/demo.h5')
demo

InstrumentID,BJ430017,BJ430047,BJ430090,BJ430139,BJ430198,BJ430300,BJ430418,BJ430425,BJ430476,BJ430478,...,SZ301586,SZ301587,SZ301588,SZ301589,SZ301591,SZ301596,SZ301603,SZ301606,SZ301608,SZ301611
date,,,,,,,,,,,,,,,,,,,,,
20200102,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20200103,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20200106,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20200107,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20200108,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20221226,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20221227,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20221228,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20221229,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20221230,NaN,29.876942,29.829333,29.57906,29.547,30.261792,29.641038,NaN,30.376602,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
demo_v2 = demo.loc[20210101:202201001, ['SH600000', 'SZ000001']]
demo_v2

InstrumentID    SH600000     SZ000001
date
20210104      129.894400  2065.492800
20210105      129.760400  2017.742200
20210106      131.637100  2172.098900
20210107      131.503100  2209.855200
20210108      131.771200  2204.302800
...                  ...          ...
20221226      105.536500  1454.725200
20221227      107.320200  1493.457100
20221228      108.509400  1496.874600
20221229      107.617500  1484.343700
20221230      108.212072  1499.152962

[485 rows x 2 columns]

In [11]:
demo.corr()['SH600000']

InstrumentID
BJ430017   NaN
BJ430047   NaN
BJ430090   NaN
BJ430139   NaN
BJ430198   NaN
            ..
SZ301596   NaN
SZ301603   NaN
SZ301606   NaN
SZ301608   NaN
SZ301611   NaN
Name: SH600000, Length: 5602, dtype: float64

### 最简单方法

In [5]:
demo_v2.corr()

InstrumentID  SH600000  SZ000001
InstrumentID
SH600000      1.000000  0.949523
SZ000001      0.949523  1.000000

### 其他方法

In [9]:
corr = ((demo_v2.iloc[:, 0] * demo_v2.iloc[:, 1]).mean() - demo_v2.iloc[:, 0].mean() * demo_v2.iloc[:, 1].mean()) / (demo_v2.iloc[:, 0].std()*demo_v2.iloc[:, 1].std() + 1e-10)
corr

0.9475655002334518