## 测试上午和下午的动量和反转情况

In [2]:
import pandas as pd
import numpy as np
from tqdm.notebook import tqdm
tqdm.pandas

In [10]:
close23 = pd.read_hdf('/mnt/datadisk2/aglv/aglv/lab_aglv/data2023.h5')['Close']
close23

Date      InstrumentID  EndTime
20230103  SZ000001      09:31      13.16
                        09:32      13.14
                        09:33      13.17
                        09:34      13.20
                        09:35      13.19
                                   ...
20231012  SH689009      14:56      33.88
                        14:57      33.89
                        14:58      33.89
                        14:59      33.89
                        15:00      33.77
Name: Close, Length: 222608001, dtype: float64

In [32]:
eg = close23.unstack()
eg

EndTime                09:30  09:31  09:32  09:33  09:34  09:35  09:36  09:37  \
Date     InstrumentID
20230103 SH600000        NaN   7.22   7.23   7.24   7.25   7.23   7.23   7.22
         SH600004        NaN  14.91  14.92  14.87  14.99  14.87  14.82  14.75
         SH600006        NaN   5.54   5.53   5.57   5.56   5.57   5.56   5.56
         SH600007        NaN  15.78  15.82  15.87  15.80  15.80  15.83  15.85
         SH600008        NaN   2.83   2.83   2.84   2.83   2.83   2.84   2.84
...                      ...    ...    ...    ...    ...    ...    ...    ...
20231012 SZ301533      41.31  41.09  41.21  41.06  41.07  40.91  40.92  40.83
         SZ301548      62.07  61.83  61.67  61.71  61.65  61.64  61.70  61.62
         SZ301550      50.19  49.20  49.32  48.75  48.80  48.90  49.17  49.10
         SZ301558      14.50  14.61  14.56  14.61  14.30  14.32  14.38  14.28
         SZ301559      23.00  22.83  22.60  22.99  23.16  23.07  22.80  22.92

EndTime                09:38  09:39  ...  14:51  14:52  14:53  14:54  14:55  \
Date     InstrumentID                ...
20230103 SH600000       7.19   7.19  ...   7.23   7.24   7.24   7.24   7.24
         SH600004      14.75  14.69  ...  14.54  14.55  14.56  14.58  14.58
         SH600006       5.54   5.54  ...   5.64   5.64   5.65   5.64   5.64
         SH600007      15.78  15.79  ...  16.14  16.14  16.13  16.14  16.13
         SH600008       2.83   2.83  ...   2.88   2.88   2.89   2.89   2.89
...                      ...    ...  ...    ...    ...    ...    ...    ...
20231012 SZ301533      40.83  40.89  ...  41.47  41.46  41.46  41.45  41.44
         SZ301548      61.53  61.11  ...  61.49  61.47  61.45  61.43  61.39
         SZ301550      49.72  49.63  ...  51.15  51.00  50.65  50.93  50.68
         SZ301558      14.32  14.35  ...  14.10  14.11  14.12  14.09  14.09
         SZ301559      23.16  23.23  ...  22.67  22.69  22.70  22.70  22.72

EndTime                14:56  14:57  14:58  14:59  15:00
Date     InstrumentID
20230103 SH600000       7.24   7.24   7.24   7.24   7.23
         SH600004      14.57  14.56  14.56  14.56  14.56
         SH600006       5.64   5.65   5.65   5.65   5.66
         SH600007      16.16  16.15  16.15  16.15  16.13
         SH600008       2.88   2.89   2.89   2.89   2.88
...                      ...    ...    ...    ...    ...
20231012 SZ301533      41.43  41.39  41.39  41.39  41.40
         SZ301548      61.38  61.37  61.34  61.34  61.33
         SZ301550      50.40  50.21  50.18  50.18  50.30
         SZ301558      14.08  14.01  14.00  14.00  14.01
         SZ301559      22.72  22.69  22.69  22.69  22.69

[925896 rows x 241 columns]

In [36]:
min30 = eg.groupby(level='Date').apply(lambda x: x.iloc[:, 30] / x.iloc[:, 1] - 1)
min30

Date      Date      InstrumentID
20230103  20230103  SH600000       -0.001385
                    SH600004       -0.019450
                    SH600006        0.005415
                    SH600007        0.025349
                    SH600008        0.003534
                                      ...
20231012  20231012  SZ301533       -0.009005
                    SZ301548       -0.016012
                    SZ301550        0.034350
                    SZ301558       -0.036277
                    SZ301559        0.002628
Length: 925896, dtype: float64

In [38]:
min30.index.names = ['a', 'Date', 'InstrumentID']
idnew = min30.index.droplevel('a')
min30.index = idnew
min30 = min30.unstack()
min30

InstrumentID,SH600000,SH600004,SH600006,SH600007,SH600008,SH600009,SH600010,SH600011,SH600012,SH600015,...,SZ301519,SZ301520,SZ301525,SZ301528,SZ301529,SZ301533,SZ301548,SZ301550,SZ301558,SZ301559
Date,,,,,,,,,,,,,,,,,,,,,
20230103,-0.001385,-0.019450,0.005415,0.025349,0.003534,-0.006787,0.000000,0.022339,0.005464,-0.001931,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20230104,0.005517,0.001385,0.005319,0.016822,0.006944,-0.001611,0.005181,-0.016477,0.006849,0.005758,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20230105,0.000000,0.026010,-0.006993,0.007313,0.000000,0.026409,0.005155,0.007663,-0.005398,-0.001894,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20230106,-0.004071,-0.016779,0.012389,-0.025424,0.000000,-0.026687,0.005181,0.030730,-0.004054,-0.003788,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20230109,0.001364,0.012943,0.010582,-0.000621,0.000000,-0.001741,0.000000,-0.025907,0.005362,-0.001901,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20230928,-0.001397,-0.009786,0.010909,0.000513,0.003534,-0.006619,0.000000,-0.006305,-0.006312,-0.005217,...,0.006203,-0.019975,0.003957,-0.001282,0.021734,0.002756,0.015568,0.021005,-0.034719,NaN
20231009,-0.004261,-0.012670,0.001776,0.002074,0.000000,-0.008805,-0.005780,0.005102,-0.004541,0.003559,...,-0.009053,-0.010495,-0.003929,-0.008146,-0.017725,-0.004660,-0.005691,-0.004375,-0.062874,NaN
20231010,-0.005642,0.000000,0.003534,-0.010428,-0.003534,0.003490,-0.011494,-0.015228,-0.009009,-0.008757,...,-0.002944,-0.026000,-0.017830,0.011946,0.010110,-0.003998,-0.007060,0.053396,0.074409,NaN
20231011,0.005690,0.000923,-0.008741,0.005247,-0.003546,0.000268,0.000000,0.003881,-0.014599,-0.001764,...,-0.017227,0.039939,0.005103,-0.003767,0.000000,0.005565,0.005811,0.009267,0.052891,-0.014233
20231012,0.008463,-0.001847,0.014159,0.000000,0.003559,0.004038,0.011696,-0.002591,0.011982,0.001754,...,-0.002183,-0.013658,0.004854,0.004662,-0.004718,-0.009005,-0.016012,0.034350,-0.036277,0.002628

In [40]:
min30_updown = min30 / min30.abs()
min30_updown.sum(axis=0)

InstrumentID
SH600000    -4.0
SH600004   -10.0
SH600006   -10.0
SH600007    12.0
SH600008    -3.0
            ...
SZ301533    -4.0
SZ301548    -1.0
SZ301550     7.0
SZ301558    -1.0
SZ301559     0.0
Length: 5111, dtype: float64

In [13]:
morn_p = eg.loc[:, :'11:30']
morn_p

EndTime                09:30  09:31  09:32  09:33  09:34  09:35  09:36  09:37  \
Date     InstrumentID
20230103 SH600000        NaN   7.22   7.23   7.24   7.25   7.23   7.23   7.22
         SH600004        NaN  14.91  14.92  14.87  14.99  14.87  14.82  14.75
         SH600006        NaN   5.54   5.53   5.57   5.56   5.57   5.56   5.56
         SH600007        NaN  15.78  15.82  15.87  15.80  15.80  15.83  15.85
         SH600008        NaN   2.83   2.83   2.84   2.83   2.83   2.84   2.84
...                      ...    ...    ...    ...    ...    ...    ...    ...
20231012 SZ301533      41.31  41.09  41.21  41.06  41.07  40.91  40.92  40.83
         SZ301548      62.07  61.83  61.67  61.71  61.65  61.64  61.70  61.62
         SZ301550      50.19  49.20  49.32  48.75  48.80  48.90  49.17  49.10
         SZ301558      14.50  14.61  14.56  14.61  14.30  14.32  14.38  14.28
         SZ301559      23.00  22.83  22.60  22.99  23.16  23.07  22.80  22.92

EndTime                09:38  09:39  ...  11:21  11:22  11:23  11:24  11:25  \
Date     InstrumentID                ...
20230103 SH600000       7.19   7.19  ...   7.22   7.23   7.23   7.23   7.23
         SH600004      14.75  14.69  ...  14.39  14.39  14.39  14.38  14.39
         SH600006       5.54   5.54  ...   5.60   5.59   5.60   5.60   5.61
         SH600007      15.78  15.79  ...  16.16  16.21  16.18  16.18  16.21
         SH600008       2.83   2.83  ...   2.86   2.86   2.87   2.86   2.86
...                      ...    ...  ...    ...    ...    ...    ...    ...
20231012 SZ301533      40.83  40.89  ...  40.99  40.97  40.97  40.97  40.98
         SZ301548      61.53  61.11  ...  60.83  60.79  60.77  60.77  60.77
         SZ301550      49.72  49.63  ...  50.68  50.45  50.35  50.34  50.34
         SZ301558      14.32  14.35  ...  13.91  13.88  13.86  13.88  13.89
         SZ301559      23.16  23.23  ...  22.92  22.89  22.83  22.90  22.91

EndTime                11:26  11:27  11:28  11:29  11:30
Date     InstrumentID
20230103 SH600000       7.23   7.24   7.23   7.24   7.24
         SH600004      14.39  14.40  14.41  14.41  14.42
         SH600006       5.60   5.60   5.61   5.60   5.61
         SH600007      16.21  16.20  16.20  16.22  16.25
         SH600008       2.87   2.86   2.86   2.86   2.87
...                      ...    ...    ...    ...    ...
20231012 SZ301533      41.04  40.96  41.05  41.01  41.00
         SZ301548      60.81  60.88  60.89  60.85  60.85
         SZ301550      50.33  50.40  50.36  50.45  50.70
         SZ301558      13.91  14.05  14.06  14.04  14.08
         SZ301559      22.88  22.90  22.91  22.95  22.95

[925896 rows x 121 columns]

In [17]:
morn_ret = morn_p.groupby(level='Date').apply(lambda x: x.iloc[:, -1] / x.iloc[:, 1] -1)
morn_ret

Date      Date      InstrumentID
20230103  20230103  SH600000        0.002770
                    SH600004       -0.032864
                    SH600006        0.012635
                    SH600007        0.029785
                    SH600008        0.014134
                                      ...
20231012  20231012  SZ301533       -0.002190
                    SZ301548       -0.015850
                    SZ301550        0.030488
                    SZ301558       -0.036277
                    SZ301559        0.005256
Length: 925896, dtype: float64

In [25]:
# morn_ret.index.names = ['a', 'Date', 'InstrumentID']
# eg = morn_ret.index.droplevel('a')
morn_ret.index = eg
morn_ret =  morn_ret.unstack()
morn_ret

InstrumentID,SH600000,SH600004,SH600006,SH600007,SH600008,SH600009,SH600010,SH600011,SH600012,SH600015,...,SZ301519,SZ301520,SZ301525,SZ301528,SZ301529,SZ301533,SZ301548,SZ301550,SZ301558,SZ301559
Date,,,,,,,,,,,,,,,,,,,,,
20230103,0.002770,-0.032864,0.012635,0.029785,0.014134,-0.008702,0.005208,0.039422,0.001366,0.003861,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20230104,0.011034,0.013850,0.003546,0.017445,0.003472,0.007337,0.005181,-0.012674,0.010959,0.013436,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20230105,-0.005427,0.016427,-0.005245,0.006703,-0.003436,0.035271,0.005155,0.001277,-0.004049,-0.003788,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20230106,-0.004071,-0.012752,0.007080,-0.019976,-0.003448,-0.014979,0.005181,0.014085,-0.002703,-0.003788,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20230109,0.000000,0.017030,0.005291,-0.006211,0.000000,0.009225,0.000000,-0.025907,0.009383,0.001901,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20230928,-0.004190,-0.010676,0.005455,-0.006160,0.003534,-0.005825,0.000000,-0.010088,-0.000902,-0.003478,...,0.009512,-0.047441,-0.031385,-0.015152,0.034376,-0.014010,0.006197,0.027934,-0.015159,NaN
20231009,-0.002841,-0.020814,0.000000,0.000518,-0.003521,-0.009338,-0.005780,0.003827,0.007266,0.008897,...,-0.016461,0.047158,-0.012816,-0.010390,-0.029331,-0.011883,-0.012458,0.000417,-0.085030,NaN
20231010,-0.007052,-0.007373,0.003534,-0.008342,-0.003534,-0.000537,-0.011494,-0.016497,-0.008108,-0.008757,...,-0.007149,-0.041286,-0.016597,-0.000483,-0.012967,-0.019050,-0.017101,0.032938,0.030598,NaN
20231011,-0.001422,-0.008303,-0.008741,-0.002099,-0.003546,-0.006972,-0.005814,-0.009056,-0.020985,-0.007055,...,-0.009475,0.023259,0.019160,-0.008141,0.001794,0.004113,0.001776,0.008237,0.011989,-0.039854
20231012,0.009873,0.002770,0.030088,0.002098,0.003559,0.004845,0.011696,0.009067,0.000922,0.005263,...,-0.006114,-0.046262,0.012283,0.005618,0.007639,-0.002190,-0.015850,0.030488,-0.036277,0.005256

In [14]:
afno_p = eg.loc[:, '13:00':]
afno_p

EndTime                13:01  13:02  13:03  13:04  13:05  13:06  13:07  13:08  \
Date     InstrumentID
20230103 SH600000       7.24   7.23   7.22   7.21   7.21   7.21   7.20   7.20
         SH600004      14.43  14.42  14.45  14.43  14.44  14.43  14.43  14.43
         SH600006       5.62   5.61   5.62   5.61   5.62   5.62   5.62   5.61
         SH600007      16.22  16.16  16.17  16.17  16.18  16.19  16.17  16.15
         SH600008       2.86   2.87   2.86   2.87   2.86   2.86   2.87   2.86
...                      ...    ...    ...    ...    ...    ...    ...    ...
20231012 SZ301533      41.09  41.05  41.07  41.08  41.14  41.06  41.06  41.06
         SZ301548      60.78  60.75  60.81  61.20  61.26  61.18  61.16  61.11
         SZ301550      50.50  50.33  50.20  50.16  50.39  50.18  50.40  50.42
         SZ301558      14.05  14.01  14.01  13.93  13.89  13.93  13.95  13.99
         SZ301559      23.05  22.97  22.98  23.00  22.97  22.96  22.93  22.88

EndTime                13:09  13:10  ...  14:51  14:52  14:53  14:54  14:55  \
Date     InstrumentID                ...
20230103 SH600000       7.22   7.21  ...   7.23   7.24   7.24   7.24   7.24
         SH600004      14.44  14.44  ...  14.54  14.55  14.56  14.58  14.58
         SH600006       5.61   5.61  ...   5.64   5.64   5.65   5.64   5.64
         SH600007      16.15  16.15  ...  16.14  16.14  16.13  16.14  16.13
         SH600008       2.86   2.87  ...   2.88   2.88   2.89   2.89   2.89
...                      ...    ...  ...    ...    ...    ...    ...    ...
20231012 SZ301533      41.10  41.10  ...  41.47  41.46  41.46  41.45  41.44
         SZ301548      61.18  61.22  ...  61.49  61.47  61.45  61.43  61.39
         SZ301550      50.39  50.35  ...  51.15  51.00  50.65  50.93  50.68
         SZ301558      13.90  13.97  ...  14.10  14.11  14.12  14.09  14.09
         SZ301559      22.86  22.88  ...  22.67  22.69  22.70  22.70  22.72

EndTime                14:56  14:57  14:58  14:59  15:00
Date     InstrumentID
20230103 SH600000       7.24   7.24   7.24   7.24   7.23
         SH600004      14.57  14.56  14.56  14.56  14.56
         SH600006       5.64   5.65   5.65   5.65   5.66
         SH600007      16.16  16.15  16.15  16.15  16.13
         SH600008       2.88   2.89   2.89   2.89   2.88
...                      ...    ...    ...    ...    ...
20231012 SZ301533      41.43  41.39  41.39  41.39  41.40
         SZ301548      61.38  61.37  61.34  61.34  61.33
         SZ301550      50.40  50.21  50.18  50.18  50.30
         SZ301558      14.08  14.01  14.00  14.00  14.01
         SZ301559      22.72  22.69  22.69  22.69  22.69

[925896 rows x 120 columns]

In [26]:
afno_ret = afno_p.groupby(level='Date').apply(lambda x: x.iloc[:, -1] / x.iloc[:, 0] -1)
afno_ret.index.names = ['a', 'Date', 'InsrumentID']
afno_ret.index = afno_ret.index.droplevel('a')
afno_ret = afno_ret.unstack()
afno_ret

InsrumentID,SH600000,SH600004,SH600006,SH600007,SH600008,SH600009,SH600010,SH600011,SH600012,SH600015,...,SZ301519,SZ301520,SZ301525,SZ301528,SZ301529,SZ301533,SZ301548,SZ301550,SZ301558,SZ301559
Date,,,,,,,,,,,,,,,,,,,,,
20230103,-0.001381,0.009009,0.007117,-0.005549,0.006993,-0.012465,-0.005155,-0.002522,-0.004076,0.003854,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20230104,-0.002729,-0.002048,-0.001764,0.011043,0.000000,0.000887,0.000000,-0.003846,-0.001353,0.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20230105,0.001362,0.013504,-0.003521,-0.003634,-0.003448,0.003613,-0.010256,0.005115,0.000000,0.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20230106,-0.001361,-0.005453,-0.003515,0.002480,-0.006920,-0.000526,-0.005155,-0.010114,-0.006766,-0.001901,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20230109,0.000000,0.024866,0.003509,0.002497,-0.003460,0.007748,0.010363,-0.003989,0.003979,0.001898,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20230928,-0.005602,0.006289,0.003610,0.001034,0.000000,0.008517,-0.005780,0.002548,0.002710,-0.003484,...,-0.005330,-0.025714,0.002881,0.003195,-0.005565,-0.004422,-0.011992,-0.022050,-0.042446,NaN
20231009,0.001425,-0.002773,0.005338,-0.005181,0.000000,-0.000809,0.000000,0.000000,0.003613,0.001764,...,-0.007535,-0.041426,0.003220,-0.015038,-0.004782,0.001886,-0.010110,0.018727,-0.051499,NaN
20231010,-0.001425,0.003707,0.008818,-0.003676,-0.007067,-0.002687,-0.011561,-0.007722,-0.010909,-0.003527,...,-0.015705,-0.021901,-0.001735,0.000965,-0.004907,-0.005031,-0.013384,-0.008520,-0.022297,NaN
20231011,0.001427,-0.000931,-0.010563,-0.002096,0.000000,-0.003778,0.000000,0.001309,0.003724,-0.001779,...,-0.008243,-0.011171,-0.027201,0.029688,0.012291,-0.005539,0.001611,0.057551,0.026499,0.014831
20231012,0.001403,0.001842,0.000000,-0.008359,-0.003546,0.001073,-0.005780,0.003856,-0.001843,-0.001748,...,0.013187,0.015156,-0.000882,0.001307,-0.010486,0.007544,0.009049,-0.003960,-0.002847,-0.015618

In [28]:
eg = afno_ret.corrwith(morn_ret)
eg[eg > 0]

InsrumentID
SH600000    0.123286
SH600004    0.005904
SH600006    0.041818
SH600008    0.042061
SH600015    0.040168
              ...
SZ301519    0.133029
SZ301520    0.078929
SZ301525    0.161051
SZ301528    0.332251
SZ301558    0.534829
Length: 2821, dtype: float64

In [29]:
eg[eg < 0]

InsrumentID
SH600007   -0.061891
SH600009   -0.013901
SH600010   -0.015733
SH600011   -0.004953
SH600012   -0.080944
              ...
SZ301529   -0.279590
SZ301533   -0.026396
SZ301548   -0.498958
SZ301550   -0.307571
SZ301559   -1.000000
Length: 2290, dtype: float64