## 换手率分布均匀度  分钟级数据

In [1]:
import pandas as pd
import numpy as np
from tqdm.notebook import tqdm
tqdm.pandas()

/mnt/datadisk2/aglv/anaconda3/lib/python3.8/site-packages/tqdm/std.py:668: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  from pandas import Panel

In [2]:
data21_23 = pd.read_hdf('/mnt/datadisk2/aglv/aglv/lab_aglv/data21_23.h5')
data21_23

                                Open  Close   High    Low  LastVolume  \
Date     InstrumentID EndTime
20210104 SZ000001     09:31    19.10  18.90  19.10  18.82   3155510.0
                      09:32    18.90  18.80  18.90  18.78   1791334.0
                      09:33    18.80  18.84  18.85  18.81   1656900.0
                      09:34    18.84  18.67  18.82  18.65   2376914.0
                      09:35    18.67  18.57  18.65  18.50   2616000.0
...                              ...    ...    ...    ...         ...
20231012 SH689009     14:56    33.94  33.88  33.94  33.88     23275.0
                      14:57    33.92  33.89  33.92  33.86      9297.0
                      14:58    33.89  33.89  33.89  33.89         0.0
                      14:59    33.89  33.89  33.89  33.89         0.0
                      15:00    33.77  33.77  33.77  33.77     62011.0

                               LastTurnOver
Date     InstrumentID EndTime
20210104 SZ000001     09:31     59855405.18
                      09:32     33745895.32
                      09:33     31190135.00
                      09:34     44535547.45
                      09:35     48631903.70
...                                     ...
20231012 SH689009     14:56       789311.00
                      14:57       315093.00
                      14:58            0.00
                      14:59            0.00
                      15:00      2094111.00

[751830321 rows x 6 columns]

In [3]:
def turn_std(vol:pd.DataFrame):
    def _turn_std(vol_daily:pd.DataFrame):
        vol_daily_percent = vol_daily / vol_daily.sum()
        vol_std = vol_daily_percent.std()

        return vol_std
    
    return vol.groupby(level='Date').progress_apply(_turn_std)

In [4]:
vol_21_23 = data21_23['LastVolume'].unstack(level='InstrumentID')
vol_21_23

InstrumentID       SH600000  SH600004    SH600006  SH600007   SH600008  \
Date     EndTime
20210104 09:31    1727980.0  257345.0  10138000.0   30600.0  1489000.0
         09:32     865050.0  255293.0   5092700.0    3400.0   718700.0
         09:33     877830.0  172506.0   6881859.0    4800.0   317300.0
         09:34     835670.0  225664.0   3533000.0   11100.0   165400.0
         09:35     436000.0  164867.0   2236900.0   23900.0   598760.0
...                     ...       ...         ...       ...        ...
20231012 14:56     208100.0   53500.0    199400.0    7600.0   187700.0
         14:57      37650.0   70570.0     97100.0   18900.0   251800.0
         14:58          0.0       0.0         0.0       0.0        0.0
         14:59          0.0       0.0         0.0       0.0        0.0
         15:00     783409.0   96900.0    247700.0   21400.0   608700.0

InstrumentID      SH600009   SH600010   SH600011  SH600012   SH600015  ...  \
Date     EndTime                                                       ...
20210104 09:31    390317.0  3122500.0  1089300.0  145500.0  1319700.0  ...
         09:32    325080.0  2368340.0   638800.0   47500.0   443500.0  ...
         09:33    256800.0  1626100.0   760900.0   21300.0   214400.0  ...
         09:34    159200.0  1754700.0   571700.0   33000.0   169100.0  ...
         09:35    347600.0  1981840.0  1363400.0   45400.0   615100.0  ...
...                    ...        ...        ...       ...        ...  ...
20231012 14:56     75952.0  2682200.0   163000.0    6300.0   223100.0  ...
         14:57     45948.0   618500.0   209300.0   12500.0   386700.0  ...
         14:58         0.0        0.0        0.0       0.0        0.0  ...
         14:59         0.0        0.0        0.0       0.0        0.0  ...
         15:00     78600.0  3681200.0   680000.0   18000.0   400700.0  ...

InstrumentID      SZ301519  SZ301520  SZ301525  SZ301528  SZ301529  SZ301533  \
Date     EndTime
20210104 09:31         NaN       NaN       NaN       NaN       NaN       NaN
         09:32         NaN       NaN       NaN       NaN       NaN       NaN
         09:33         NaN       NaN       NaN       NaN       NaN       NaN
         09:34         NaN       NaN       NaN       NaN       NaN       NaN
         09:35         NaN       NaN       NaN       NaN       NaN       NaN
...                    ...       ...       ...       ...       ...       ...
20231012 14:56     38900.0   17200.0   14406.0   12900.0   53300.0    8600.0
         14:57     27400.0   39900.0    5000.0    8100.0   46502.0    7300.0
         14:58         0.0       0.0       0.0       0.0       0.0       0.0
         14:59         0.0       0.0       0.0       0.0       0.0       0.0
         15:00     35500.0   49700.0   23000.0   40400.0   52500.0   22300.0

InstrumentID      SZ301548  SZ301550  SZ301558  SZ301559
Date     EndTime
20210104 09:31         NaN       NaN       NaN       NaN
         09:32         NaN       NaN       NaN       NaN
         09:33         NaN       NaN       NaN       NaN
         09:34         NaN       NaN       NaN       NaN
         09:35         NaN       NaN       NaN       NaN
...                    ...       ...       ...       ...
20231012 14:56     20500.0   23500.0  424700.0  202340.0
         14:57     15600.0   67100.0  527929.0  349243.0
         14:58         0.0       0.0       0.0       0.0
         14:59         0.0       0.0       0.0       0.0
         15:00     36600.0  106100.0  703611.0  334955.0

[161118 rows x 5175 columns]

In [5]:
eg1 = vol_21_23.xs('20210104', level='Date')
eg1

InstrumentID,SH600000,SH600004,SH600006,SH600007,SH600008,SH600009,SH600010,SH600011,SH600012,SH600015,...,SZ301519,SZ301520,SZ301525,SZ301528,SZ301529,SZ301533,SZ301548,SZ301550,SZ301558,SZ301559
EndTime,,,,,,,,,,,,,,,,,,,,,
09:31,1727980.0,257345.0,10138000.0,30600.0,1489000.0,390317.0,3122500.0,1089300.0,145500.0,1319700.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
09:32,865050.0,255293.0,5092700.0,3400.0,718700.0,325080.0,2368340.0,638800.0,47500.0,443500.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
09:33,877830.0,172506.0,6881859.0,4800.0,317300.0,256800.0,1626100.0,760900.0,21300.0,214400.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
09:34,835670.0,225664.0,3533000.0,11100.0,165400.0,159200.0,1754700.0,571700.0,33000.0,169100.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
09:35,436000.0,164867.0,2236900.0,23900.0,598760.0,347600.0,1981840.0,1363400.0,45400.0,615100.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14:56,276200.0,83915.0,1128348.0,400.0,169100.0,162991.0,670860.0,247800.0,57900.0,175927.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14:57,345462.0,75003.0,1076000.0,5733.0,192800.0,114700.0,665490.0,194200.0,88000.0,102944.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14:58,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14:59,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15:00,1210938.0,222000.0,3191400.0,7157.0,639081.0,194100.0,6305200.0,1205200.0,82100.0,336299.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
eg1.index = list(range(len(eg1.index)))
eg1

InstrumentID,SH600000,SH600004,SH600006,SH600007,SH600008,SH600009,SH600010,SH600011,SH600012,SH600015,...,SZ301519,SZ301520,SZ301525,SZ301528,SZ301529,SZ301533,SZ301548,SZ301550,SZ301558,SZ301559
0,1727980.0,257345.0,10138000.0,30600.0,1489000.0,390317.0,3122500.0,1089300.0,145500.0,1319700.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,865050.0,255293.0,5092700.0,3400.0,718700.0,325080.0,2368340.0,638800.0,47500.0,443500.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,877830.0,172506.0,6881859.0,4800.0,317300.0,256800.0,1626100.0,760900.0,21300.0,214400.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,835670.0,225664.0,3533000.0,11100.0,165400.0,159200.0,1754700.0,571700.0,33000.0,169100.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,436000.0,164867.0,2236900.0,23900.0,598760.0,347600.0,1981840.0,1363400.0,45400.0,615100.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
235,276200.0,83915.0,1128348.0,400.0,169100.0,162991.0,670860.0,247800.0,57900.0,175927.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
236,345462.0,75003.0,1076000.0,5733.0,192800.0,114700.0,665490.0,194200.0,88000.0,102944.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
237,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
238,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
239,1210938.0,222000.0,3191400.0,7157.0,639081.0,194100.0,6305200.0,1205200.0,82100.0,336299.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [13]:
def turn_std_v2(vol:pd.DataFrame, k=0.9):
    def _turn_std(vol_daily:pd.DataFrame):
        vol_daily_percent = vol_daily / vol_daily.sum()
        return vol_daily_percent[vol_daily_percent > vol_daily_percent.quantile(k)].mean()
    
    return vol.groupby(level='Date').progress_apply(_turn_std)

In [14]:
import pandas as pd
is_trading = pd.read_csv('/mnt/datadisk2/aglv/aglv/lab_aglv/is_trading.csv')
is_trading

,date,BJ430017,BJ430047,BJ430090,BJ430139,BJ430198,BJ430300,BJ430418,BJ430425,BJ430476,...,SZ301586,SZ301587,SZ301588,SZ301589,SZ301591,SZ301596,SZ301603,SZ301606,SZ301608,SZ301611
0,20171009,1,1,1,1,1.0,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
1,20171010,1,1,1,1,1.0,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
2,20171011,1,1,1,1,1.0,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
3,20171012,1,1,1,1,1.0,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
4,20171013,1,1,1,1,1.0,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1675,20240827,1,1,1,1,1.0,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
1676,20240828,1,1,1,1,1.0,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
1677,20240829,1,1,1,1,1.0,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
1678,20240830,1,1,1,1,1.0,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
1679,20240902,1,1,1,1,1.0,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1

In [31]:
# is_trading.index = [str(i) for i in is_trading.index]
# is_trading.set_index('date', inplace=True)
# is_trading.index.names = ['Date']
is_trading

,BJ430017,BJ430047,BJ430090,BJ430139,BJ430198,BJ430300,BJ430418,BJ430425,BJ430476,BJ430478,...,SZ301586,SZ301587,SZ301588,SZ301589,SZ301591,SZ301596,SZ301603,SZ301606,SZ301608,SZ301611
Date,,,,,,,,,,,,,,,,,,,,,
20171009,1,1,1,1,1.0,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
20171010,1,1,1,1,1.0,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
20171011,1,1,1,1,1.0,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
20171012,1,1,1,1,1.0,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
20171013,1,1,1,1,1.0,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20240827,1,1,1,1,1.0,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
20240828,1,1,1,1,1.0,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
20240829,1,1,1,1,1.0,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
20240830,1,1,1,1,1.0,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
20240902,1,1,1,1,1.0,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1

In [36]:
# is_trading.index = [str(i) for i in is_trading.index]
is_trading.index

Index(['20171009', '20171010', '20171011', '20171012', '20171013', '20171016',
       '20171017', '20171018', '20171019', '20171020',
       ...
       '20240820', '20240821', '20240822', '20240823', '20240826', '20240827',
       '20240828', '20240829', '20240830', '20240902'],
      dtype='object', length=1680)

In [37]:
new = turn_fa_v2.shift(1)
new = new * is_trading.loc[new.index, new.columns]
new

InstrumentID,SH600000,SH600004,SH600006,SH600007,SH600008,SH600009,SH600010,SH600011,SH600012,SH600015,...,SZ301519,SZ301520,SZ301525,SZ301528,SZ301529,SZ301533,SZ301548,SZ301550,SZ301558,SZ301559
Date,,,,,,,,,,,,,,,,,,,,,
20210104,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20210105,0.013242,0.012893,0.016778,0.017595,0.018034,0.013527,0.026073,0.011746,0.014041,0.016930,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20210106,0.013430,0.014121,0.018373,0.016314,0.015622,0.009775,0.025786,0.015406,0.015102,0.016937,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20210107,0.014294,0.012481,0.014550,0.018882,0.016853,0.013091,0.012304,0.014588,0.015769,0.019581,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20210108,0.013774,0.009911,0.015148,0.023151,0.017077,0.011588,0.026337,0.014005,0.016240,0.015661,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20230928,0.020877,0.017202,0.016182,0.014804,0.023989,0.019145,0.023854,0.015849,0.013604,0.017423,...,0.018585,0.016910,0.013654,0.018097,0.016609,0.016071,0.019115,0.013023,NaN,NaN
20231009,0.018022,0.017047,0.022270,0.018795,0.023471,0.016095,0.024851,0.016561,0.014413,0.017024,...,0.016150,0.018463,0.013833,0.015268,0.014155,0.020328,0.016488,0.017522,0.019683,NaN
20231010,0.018818,0.012985,0.017799,0.010468,0.021732,0.016934,0.020753,0.014955,0.017145,0.017958,...,0.016761,0.015894,0.016137,0.017089,0.016796,0.013988,0.016242,0.014884,0.017087,NaN
20231011,0.019940,0.015512,0.019815,0.015819,0.024847,0.018656,0.027482,0.015756,0.018862,0.019235,...,0.015337,0.017918,0.017379,0.020234,0.014694,0.015785,0.011822,0.019094,0.020487,NaN
20231012,0.020497,0.014929,0.020106,0.017183,0.022280,0.013771,0.018895,0.013545,0.017976,0.015366,...,0.018357,0.019662,0.015950,0.015719,0.017932,0.020088,0.015737,0.016973,0.018651,0.016803

In [40]:
datadaily = pd.read_hdf('/mnt/datadisk2/aglv/aglv/lab_aglv/datadaily_aglv.h5')
datadaily

                          adjopen    adjclose      adjlow     adjhigh  \
date     InstrumentID
20171009 SH600000      161.907300  159.101000  158.613000  162.151300
         SH600001             NaN   13.690500         NaN         NaN
         SH600002             NaN   11.169600         NaN         NaN
         SH600003             NaN    5.483800         NaN         NaN
         SH600004       33.310500   33.008800   32.782600   33.536800
...                           ...         ...         ...         ...
20240829 SZ301596       91.134144   93.605324   91.074236   94.503935
         SZ301603      101.151087  104.285819  101.151087  106.301004
         SZ301606       52.613296   54.386987   52.613296   55.955304
         SZ301608       44.045843   45.164494   44.045843   46.488090
         SZ301611      231.468300  244.948275  225.659250  247.629375

                             vol       mkt_cap
date     InstrumentID
20171009 SH600000      521490.81  3.664731e+11
         SH600001            NaN           NaN
         SH600002            NaN           NaN
         SH600003            NaN           NaN
         SH600004      200125.67  2.717018e+10
...                          ...           ...
20240829 SZ301596       13902.00  8.612199e+08
         SZ301603       53173.01  8.548240e+08
         SZ301606       79270.78  9.090974e+08
         SZ301608       43084.89  8.943629e+08
         SZ301611      256045.25  1.854934e+09

[7360300 rows x 6 columns]

In [41]:
closedaily = datadaily['adjclose'].unstack(level='InstrumentID')
closedaily

InstrumentID,BJ430017,BJ430047,BJ430090,BJ430139,BJ430198,BJ430300,BJ430418,BJ430425,BJ430476,BJ430478,...,SZ301586,SZ301587,SZ301588,SZ301589,SZ301591,SZ301596,SZ301603,SZ301606,SZ301608,SZ301611
date,,,,,,,,,,,,,,,,,,,,,
20171009,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20171010,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20171011,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20171012,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20171013,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20240823,17.959935,25.359466,11.379577,25.525705,14.611485,32.237887,61.908928,10.578368,13.259199,24.619777,...,NaN,50.182204,76.160027,31.827272,660.490820,91.643356,99.919585,53.210750,44.310562,206.146800
20240826,17.789376,25.503204,11.498944,25.587963,14.611485,32.284677,62.548578,10.787611,13.298838,24.879388,...,NaN,51.426963,77.420259,32.769126,669.812721,91.373773,100.759245,53.696181,44.532584,210.019500
20240827,17.959935,25.585340,11.419366,24.903127,14.133802,31.629625,62.685646,10.508621,12.089853,25.117365,...,NaN,49.006599,76.664120,33.055599,657.989822,90.160648,99.023947,51.362376,43.764045,212.775075
20240828,18.062271,25.318398,11.498944,24.467322,14.133802,31.816783,63.782188,10.659740,12.010575,24.706314,...,185.423798,49.121855,77.588290,34.644592,665.947543,91.793125,102.074713,52.501273,44.592360,225.286875
20240829,18.232831,25.010388,11.339789,22.879748,14.021406,32.331466,64.056323,10.787611,12.089853,25.247171,...,171.730597,50.366613,78.302422,34.644592,675.951534,93.605324,104.285819,54.386987,45.164494,244.948275

In [44]:
# closedaily.index = [str(i) for i in closedaily.index]

In [51]:
close_pct = closedaily.pct_change().loc[new.index, new.columns]
close_pct

InstrumentID,SH600000,SH600004,SH600006,SH600007,SH600008,SH600009,SH600010,SH600011,SH600012,SH600015,...,SZ301519,SZ301520,SZ301525,SZ301528,SZ301529,SZ301533,SZ301548,SZ301550,SZ301558,SZ301559
Date,,,,,,,,,,,,,,,,,,,,,
20210104,0.001033,-0.006369,-0.023307,-0.004016,0.010602,0.024187,0.008544,0.004462,-0.019417,-0.006400,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20210105,-0.001032,-0.016381,-0.036874,0.012903,0.000000,-0.002452,-0.008472,-0.022222,0.006601,0.008052,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20210106,0.014463,-0.019551,-0.045045,0.009554,-0.006996,0.002458,0.000000,0.006818,0.040987,0.001597,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20210107,-0.001018,-0.052438,-0.005898,-0.021293,-0.014083,-0.021164,0.000000,-0.006772,-0.039373,-0.004785,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20210108,0.002039,0.027281,-0.027283,-0.000806,0.032141,0.001714,0.000000,0.015910,-0.001636,0.001603,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20230928,-0.004208,-0.000892,0.014599,-0.003088,0.003534,0.007177,0.005848,-0.005057,-0.002695,0.000000,...,0.004139,-0.147500,-0.033318,-0.004696,0.035436,0.003519,0.008878,0.022617,NaN,NaN
20231009,-0.009859,-0.036607,0.016187,-0.008776,-0.007042,-0.021642,0.000000,0.000000,0.000901,-0.006993,...,-0.022671,-0.028392,-0.018438,-0.026424,-0.014421,-0.006779,-0.034441,0.051321,-0.232190,NaN
20231010,-0.002845,0.003707,0.012389,-0.011979,-0.003546,0.001079,-0.005814,-0.020330,-0.020702,-0.005282,...,-0.021932,-0.099328,-0.022560,0.005695,-0.025770,-0.022594,-0.027027,0.022059,-0.005498,NaN
20231011,0.001427,-0.009234,-0.017483,0.003690,-0.003559,-0.005120,0.000000,-0.007782,-0.009191,-0.007080,...,-0.014230,0.011272,-0.005311,0.015422,0.015467,-0.005779,0.004199,0.035572,0.017277,NaN
20231012,0.017094,0.013979,0.030249,-0.003151,0.003571,0.011105,0.005848,0.020915,0.004638,0.017825,...,0.008311,-0.011297,-0.010680,0.000119,-0.020971,0.002664,-0.013670,-0.029332,-0.048234,-0.05261

In [75]:
def destop(factor:pd.DataFrame):
    factor.index = [str(i) for i in factor.index]
    res = factor.shift(1) * is_trading.loc[factor.index, factor.columns]
    res.index.names = ['Date']
    return res

In [79]:
new_v2 = destop(turn_fa_v2 * close_pct)
new_v2

InstrumentID,SH600000,SH600004,SH600006,SH600007,SH600008,SH600009,SH600010,SH600011,SH600012,SH600015,...,SZ301519,SZ301520,SZ301525,SZ301528,SZ301529,SZ301533,SZ301548,SZ301550,SZ301558,SZ301559
Date,,,,,,,,,,,,,,,,,,,,,
20210104,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20210105,0.000014,-0.000082,-0.000391,-0.000071,0.000191,0.000327,0.000223,0.000052,-0.000273,-0.000108,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20210106,-0.000014,-0.000231,-0.000677,0.000211,0.000000,-0.000024,-0.000218,-0.000342,0.000100,0.000136,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20210107,0.000207,-0.000244,-0.000655,0.000180,-0.000118,0.000032,0.000000,0.000099,0.000646,0.000031,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20210108,-0.000014,-0.000520,-0.000089,-0.000493,-0.000240,-0.000245,0.000000,-0.000095,-0.000639,-0.000075,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20230928,-0.000058,0.000046,-0.000059,-0.000158,0.000000,0.000144,0.000000,-0.000139,-0.000334,-0.000121,...,0.000194,0.004846,0.000442,-0.000160,-0.000506,-0.000386,-0.000653,0.000280,NaN,NaN
20231009,-0.000076,-0.000015,0.000325,-0.000058,0.000083,0.000116,0.000145,-0.000084,-0.000039,0.000000,...,0.000067,-0.002723,-0.000461,-0.000072,0.000502,0.000072,0.000146,0.000396,NaN,NaN
20231010,-0.000186,-0.000475,0.000288,-0.000092,-0.000153,-0.000366,0.000000,0.000000,0.000015,-0.000126,...,-0.000380,-0.000451,-0.000298,-0.000452,-0.000242,-0.000095,-0.000559,0.000764,-0.003967,NaN
20231011,-0.000057,0.000058,0.000245,-0.000189,-0.000088,0.000020,-0.000160,-0.000320,-0.000390,-0.000102,...,-0.000336,-0.001780,-0.000392,0.000115,-0.000379,-0.000357,-0.000320,0.000421,-0.000113,NaN
20231012,0.000029,-0.000138,-0.000352,0.000063,-0.000079,-0.000071,0.000000,-0.000105,-0.000165,-0.000109,...,-0.000261,0.000222,-0.000085,0.000242,0.000277,-0.000116,0.000066,0.000604,0.000322,NaN

In [80]:
new_v2.to_csv('/mnt/datadisk2/aglv/aglv/lab_aglv/aglv_factor/Sep/turn_cvar_posi_mul-ret__noavg_21_23_destop_min.csv')

In [59]:
new_v2.index.names = ['Date']
new_v2

InstrumentID,SH600000,SH600004,SH600006,SH600007,SH600008,SH600009,SH600010,SH600011,SH600012,SH600015,...,SZ301519,SZ301520,SZ301525,SZ301528,SZ301529,SZ301533,SZ301548,SZ301550,SZ301558,SZ301559
Date,,,,,,,,,,,,,,,,,,,,,
20210104,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20210105,0.000014,0.000082,0.000391,0.000071,0.000191,0.000327,0.000223,0.000052,0.000273,0.000108,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20210106,0.000014,0.000231,0.000677,0.000211,0.000000,0.000024,0.000218,0.000342,0.000100,0.000136,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20210107,0.000207,0.000244,0.000655,0.000180,0.000118,0.000032,0.000000,0.000099,0.000646,0.000031,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20210108,0.000014,0.000520,0.000089,0.000493,0.000240,0.000245,0.000000,0.000095,0.000639,0.000075,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20230928,0.000058,0.000046,0.000059,0.000158,0.000000,0.000144,0.000000,0.000139,0.000334,0.000121,...,0.000194,0.004846,0.000442,0.000160,0.000506,0.000386,0.000653,0.000280,NaN,NaN
20231009,0.000076,0.000015,0.000325,0.000058,0.000083,0.000116,0.000145,0.000084,0.000039,0.000000,...,0.000067,0.002723,0.000461,0.000072,0.000502,0.000072,0.000146,0.000396,NaN,NaN
20231010,0.000186,0.000475,0.000288,0.000092,0.000153,0.000366,0.000000,0.000000,0.000015,0.000126,...,0.000380,0.000451,0.000298,0.000452,0.000242,0.000095,0.000559,0.000764,0.003967,NaN
20231011,0.000057,0.000058,0.000245,0.000189,0.000088,0.000020,0.000160,0.000320,0.000390,0.000102,...,0.000336,0.001780,0.000392,0.000115,0.000379,0.000357,0.000320,0.000421,0.000113,NaN
20231012,0.000029,0.000138,0.000352,0.000063,0.000079,0.000071,0.000000,0.000105,0.000165,0.000109,...,0.000261,0.000222,0.000085,0.000242,0.000277,0.000116,0.000066,0.000604,0.000322,NaN

In [62]:
vol_21_23_sum = vol_21_23.groupby('Date').progress_apply(lambda x: x.sum())
vol_21_23_sum

HBox(children=(FloatProgress(value=0.0, max=671.0), HTML(value='')))

InstrumentID,SH600000,SH600004,SH600006,SH600007,SH600008,SH600009,SH600010,SH600011,SH600012,SH600015,...,SZ301519,SZ301520,SZ301525,SZ301528,SZ301529,SZ301533,SZ301548,SZ301550,SZ301558,SZ301559
Date,,,,,,,,,,,,,,,,,,,,,
20210104,62432839.0,19054796.0,177666533.0,1442646.0,42025495.0,21622546.0,292240933.0,64577657.0,4981785.0,26213943.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
20210105,53628977.0,20050522.0,187172217.0,1237741.0,41444498.0,19442258.0,289320702.0,69990580.0,7149617.0,31224263.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
20210106,61383724.0,18719307.0,128078021.0,2083789.0,37702163.0,19914164.0,98386092.0,49905196.0,19302460.0,27041151.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
20210107,56930332.0,44748804.0,163064770.0,1720191.0,45132313.0,22534494.0,477892939.0,47280905.0,10020341.0,25285561.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
20210108,55268355.0,25579493.0,114749333.0,1388389.0,83835742.0,16071113.0,281925909.0,45093413.0,8814379.0,20583441.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20230928,22435320.0,13720722.0,12507968.0,931090.0,25495038.0,8451965.0,112379640.0,34745655.0,4473099.0,22776551.0,...,2245353.0,9327094.0,2110189.0,1119581.0,4812943.0,1501986.0,4170837.0,11566981.0,86204902.0,0.0
20231009,27763130.0,25705006.0,18296450.0,2000625.0,35495462.0,9753725.0,106856569.0,26830342.0,3857159.0,29347698.0,...,2577361.0,7281621.0,1308925.0,858214.0,3324220.0,1049504.0,3112082.0,9220854.0,63516393.0,0.0
20231010,24095561.0,15186449.0,20956644.0,1671530.0,41336353.0,7928876.0,138338803.0,47959833.0,4143471.0,23209033.0,...,2675684.0,6853886.0,1445502.0,867955.0,4036359.0,1250522.0,2408480.0,9168723.0,45261875.0,0.0
20231011,24057412.0,13412500.0,15160200.0,1248600.0,35909812.0,8497078.0,102037528.0,43379467.0,6611448.0,27785361.0,...,2438204.0,5463111.0,1358174.0,1402093.0,3389443.0,925780.0,1655750.0,8165973.0,43096276.0,42808507.0
20231012,36346964.0,12847359.0,31254495.0,896224.0,38207782.0,7373655.0,110307072.0,46756421.0,3989016.0,34717190.0,...,1904718.0,4842290.0,1454120.0,955767.0,2835613.0,891885.0,1671335.0,4931757.0,39681692.0,19777270.0

In [67]:
vol_21_23_r5mean = vol_21_23_sum.rolling(5).mean()
vol_21_23_r5mean

InstrumentID,SH600000,SH600004,SH600006,SH600007,SH600008,SH600009,SH600010,SH600011,SH600012,SH600015,...,SZ301519,SZ301520,SZ301525,SZ301528,SZ301529,SZ301533,SZ301548,SZ301550,SZ301558,SZ301559
Date,,,,,,,,,,,,,,,,,,,,,
20210104,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20210105,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20210106,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20210107,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20210108,57928845.4,25630584.4,154146174.8,1574551.2,50028042.2,19916915.0,287953315.0,55369550.2,10053716.4,26069671.8,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20230928,27857474.8,13981453.8,9762755.0,1485529.4,31607769.0,8503864.2,134082168.2,34851715.8,5349695.2,28466082.4,...,2767878.6,8067052.6,2651140.6,1149411.2,4440757.4,1478133.0,5018248.8,11022663.8,17240980.4,0.0
20231009,26973846.6,16495639.6,11432706.8,1344469.4,27923071.0,8780837.2,114514331.4,32474578.8,5024287.0,29019977.2,...,2634517.4,9523376.8,2535662.2,1113859.8,4211456.0,1283953.6,4620775.6,11002343.2,29944259.0,0.0
20231010,25649470.2,17749676.6,13710806.8,1311395.4,30603938.2,9038269.0,115623795.2,35937315.4,4627693.0,26077533.2,...,2729048.0,8668695.2,2065952.8,1023810.6,4278921.8,1313467.0,4143973.8,10816241.2,38996634.0,0.0
20231011,26083742.6,16649533.2,15057180.6,1341155.4,33780510.8,8884704.6,113469326.0,37058939.2,5128194.4,25943186.4,...,2744862.0,8106552.4,1840298.0,1070995.4,3974716.6,1232551.8,3303699.8,10179072.6,47615889.2,8561701.4
20231012,26939677.4,16174407.2,19635151.4,1349613.8,35288889.4,8401059.8,113983922.4,39934343.6,4614838.6,27567166.6,...,2368264.0,6753600.4,1535382.0,1040722.0,3679715.6,1123935.4,2603696.8,8610857.6,55552227.6,12517155.4

In [68]:
def turn_std_v3(vol:pd.DataFrame):
    def _turn_std(vol_daily:pd.DataFrame):
        vol_daily_percent = vol_daily / vol_21_23_r5mean
        vol_std = vol_daily_percent.std()

        return vol_std
    
    return vol.groupby(level='Date').progress_apply(_turn_std)

In [19]:
def turn_std_v4(vol:pd.DataFrame, agg_num=10):
    def _assist(vol_daily:pd.DataFrame):
        vol_daily /= vol_daily.sum()
        vol_daily.index = list(range(len(vol_daily)))
        vol_daily_agg = vol_daily.groupby(vol_daily.index // agg_num).sum()

        return vol_daily_agg.std()
    
    return vol.groupby(level='Date').progress_apply(_assist)

In [22]:
def turn_std_v5(vol:pd.DataFrame, agg_num=10):
    def _assist(vol_daily:pd.DataFrame):
        vol_daily /= vol_daily.sum()
        vol_daily.index = list(range(len(vol_daily)))
        vol_daily_agg = vol_daily.groupby(vol_daily.index // agg_num).sum()

        return vol_daily_agg.diff().abs().sum()
    
    return vol.groupby(level='Date').progress_apply(_assist)

In [23]:
f_v5_1 = turn_std_v5(vol_21_23)
f_v5_1

HBox(children=(FloatProgress(value=0.0, max=671.0), HTML(value='')))

InstrumentID,SH600000,SH600004,SH600006,SH600007,SH600008,SH600009,SH600010,SH600011,SH600012,SH600015,...,SZ301519,SZ301520,SZ301525,SZ301528,SZ301529,SZ301533,SZ301548,SZ301550,SZ301558,SZ301559
Date,,,,,,,,,,,,,,,,,,,,,
20210104,0.363129,0.465673,0.399272,0.551780,0.370245,0.239447,0.683597,0.248761,0.340581,0.367148,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
20210105,0.268991,0.326431,0.317893,0.569245,0.324250,0.189988,0.926369,0.305816,0.470638,0.630580,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
20210106,0.411974,0.285838,0.348379,0.480218,0.422860,0.220242,0.298887,0.291225,0.403330,0.398962,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
20210107,0.335673,0.243785,0.528173,0.798612,0.428684,0.383504,1.139234,0.483480,0.365878,0.315487,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
20210108,0.333976,0.275532,0.379945,0.603955,0.808829,0.226054,0.729151,0.349167,0.358096,0.436625,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20230928,0.491765,0.414696,0.747470,0.672342,0.697607,0.538252,0.882130,0.401220,0.437728,0.440659,...,0.416674,0.416372,0.490246,0.528408,0.448738,0.533273,0.404239,0.467426,0.410009,0.000000
20231009,0.490298,0.427665,0.547437,0.248517,0.936364,0.439574,0.639031,0.406265,0.577892,0.549455,...,0.561152,0.449075,0.386548,0.522522,0.468646,0.409203,0.596389,0.510528,0.375669,0.000000
20231010,0.479116,0.440140,0.515153,0.430360,0.827503,0.503826,0.717021,0.529018,0.573756,0.411238,...,0.459670,0.413463,0.598822,0.434879,0.418741,0.541352,0.408008,0.447119,0.444717,0.000000
20231011,0.469867,0.589143,0.524432,0.620615,0.613325,0.409596,0.564840,0.398802,0.470306,0.273530,...,0.422926,0.335931,0.514064,0.677669,0.627231,0.675240,0.419278,0.504885,0.395932,0.416090
20231012,0.540517,0.742061,0.685863,0.701999,0.814394,0.530368,0.671380,0.502160,0.865020,0.567154,...,0.463418,0.432087,0.428003,0.487180,0.582152,0.445520,0.449377,0.446131,0.439993,0.464924

In [27]:
f_v5_2 = f_v5_1.replace(0, np.nan)
f_v5_2

InstrumentID,SH600000,SH600004,SH600006,SH600007,SH600008,SH600009,SH600010,SH600011,SH600012,SH600015,...,SZ301519,SZ301520,SZ301525,SZ301528,SZ301529,SZ301533,SZ301548,SZ301550,SZ301558,SZ301559
Date,,,,,,,,,,,,,,,,,,,,,
20210104,0.363129,0.465673,0.399272,0.551780,0.370245,0.239447,0.683597,0.248761,0.340581,0.367148,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20210105,0.268991,0.326431,0.317893,0.569245,0.324250,0.189988,0.926369,0.305816,0.470638,0.630580,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20210106,0.411974,0.285838,0.348379,0.480218,0.422860,0.220242,0.298887,0.291225,0.403330,0.398962,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20210107,0.335673,0.243785,0.528173,0.798612,0.428684,0.383504,1.139234,0.483480,0.365878,0.315487,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20210108,0.333976,0.275532,0.379945,0.603955,0.808829,0.226054,0.729151,0.349167,0.358096,0.436625,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20230928,0.491765,0.414696,0.747470,0.672342,0.697607,0.538252,0.882130,0.401220,0.437728,0.440659,...,0.416674,0.416372,0.490246,0.528408,0.448738,0.533273,0.404239,0.467426,0.410009,NaN
20231009,0.490298,0.427665,0.547437,0.248517,0.936364,0.439574,0.639031,0.406265,0.577892,0.549455,...,0.561152,0.449075,0.386548,0.522522,0.468646,0.409203,0.596389,0.510528,0.375669,NaN
20231010,0.479116,0.440140,0.515153,0.430360,0.827503,0.503826,0.717021,0.529018,0.573756,0.411238,...,0.459670,0.413463,0.598822,0.434879,0.418741,0.541352,0.408008,0.447119,0.444717,NaN
20231011,0.469867,0.589143,0.524432,0.620615,0.613325,0.409596,0.564840,0.398802,0.470306,0.273530,...,0.422926,0.335931,0.514064,0.677669,0.627231,0.675240,0.419278,0.504885,0.395932,0.416090
20231012,0.540517,0.742061,0.685863,0.701999,0.814394,0.530368,0.671380,0.502160,0.865020,0.567154,...,0.463418,0.432087,0.428003,0.487180,0.582152,0.445520,0.449377,0.446131,0.439993,0.464924

In [25]:
def factor_group(factor, group_number=10):
    '''按照因子值分组,grp1最小'''
    # fg = factor.apply(
    #     lambda x: pd.qcut(x.rank(method='first'), q=group_number, labels=False) + 1, 
    #     axis=1)
    def categorize_with_nan(x, group_number):
        if x.isna().any():
            # 保留 NaN 的逻辑
            return pd.Series(pd.qcut(x.rank(method='first').fillna(-1), q=group_number, labels=False, duplicates='drop') + 1).replace(-1, np.nan)
        else:
            return pd.qcut(x.rank(method='first'), q=group_number, labels=False) + 1
    
    fg = factor.apply(lambda x: categorize_with_nan(x, group_number), axis=1)
    
    def _factor_group(factor_daily:pd.Series):
        dic = {f'group{str(g_value)}':factor_daily[factor_daily == g_value].index.tolist() for g_value in range(1, 1+group_number)}
        return pd.Series(dic)
    
    return {'group_stock':fg.apply(_factor_group, axis=1), 'group_index':fg}

In [28]:
factor_group(f_v5_2)['group_index']

InstrumentID,SH600000,SH600004,SH600006,SH600007,SH600008,SH600009,SH600010,SH600011,SH600012,SH600015,...,SZ301519,SZ301520,SZ301525,SZ301528,SZ301529,SZ301533,SZ301548,SZ301550,SZ301558,SZ301559
Date,,,,,,,,,,,,,,,,,,,,,
20210104,2,5,3,6,3,1,8,1,2,3,...,1,1,1,1,1,1,1,1,1,1
20210105,1,2,2,7,2,1,8,1,5,7,...,1,1,1,1,1,1,1,1,1,1
20210106,4,1,2,5,4,1,1,1,3,3,...,1,1,1,1,1,1,1,1,1,1
20210107,2,1,6,8,4,3,8,6,2,1,...,1,1,1,1,1,1,1,1,1,1
20210108,1,1,1,3,5,1,4,1,1,2,...,1,1,1,1,1,1,1,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20230928,5,3,10,9,9,7,10,2,3,4,...,3,3,5,6,4,6,2,4,3,1
20231009,6,4,8,1,10,5,9,3,9,8,...,8,5,3,7,6,4,9,7,2,1
20231010,5,4,7,4,10,6,10,7,8,3,...,5,3,8,4,4,7,3,4,4,1
20231011,5,8,6,8,8,3,7,3,5,1,...,3,1,6,9,9,9,3,6,3,3
20231012,6,10,9,9,10,6,9,5,10,7,...,4,3,3,5,8,4,4,4,3,4

In [24]:
f_v5_1.to_csv('/mnt/datadisk2/aglv/aglv/lab_aglv/aglv_factor/Sep/turn_diffabs_agg10min_noavg_21_23_min.csv')

In [20]:
f_v4_1 = turn_std_v4(vol_21_23)
f_v4_1

HBox(children=(FloatProgress(value=0.0, max=671.0), HTML(value='')))

InstrumentID,SH600000,SH600004,SH600006,SH600007,SH600008,SH600009,SH600010,SH600011,SH600012,SH600015,...,SZ301519,SZ301520,SZ301525,SZ301528,SZ301529,SZ301533,SZ301548,SZ301550,SZ301558,SZ301559
Date,,,,,,,,,,,,,,,,,,,,,
20210104,0.023024,0.020582,0.049639,0.028206,0.027645,0.030875,0.045459,0.017988,0.022979,0.035552,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
20210105,0.026854,0.023156,0.050918,0.020623,0.021190,0.016551,0.061547,0.026138,0.024363,0.037740,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
20210106,0.027830,0.024021,0.033837,0.034333,0.022003,0.031021,0.018225,0.026147,0.030638,0.034478,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
20210107,0.027813,0.011792,0.032472,0.069434,0.022245,0.021029,0.067433,0.031167,0.031217,0.030429,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
20210108,0.029841,0.033911,0.038612,0.032543,0.040395,0.028747,0.082865,0.027843,0.036293,0.037937,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20230928,0.026979,0.032161,0.039309,0.039159,0.044945,0.032210,0.047241,0.018011,0.022063,0.019377,...,0.026274,0.049199,0.023520,0.023903,0.030687,0.045209,0.042830,0.046183,0.063491,0.000000
20231009,0.032496,0.025135,0.036936,0.013785,0.037614,0.041894,0.046187,0.026417,0.030839,0.028858,...,0.034011,0.035553,0.035749,0.037886,0.043291,0.022154,0.036206,0.035683,0.045936,0.000000
20231010,0.034310,0.026750,0.044504,0.025919,0.044027,0.039614,0.057975,0.022809,0.028685,0.029179,...,0.019759,0.049026,0.037981,0.051302,0.033961,0.030274,0.022750,0.051060,0.057329,0.000000
20231011,0.025695,0.022187,0.034365,0.026174,0.033274,0.021255,0.033977,0.017664,0.039448,0.011933,...,0.037716,0.052491,0.029845,0.030042,0.038573,0.034770,0.035674,0.041395,0.048592,0.052100
20231012,0.050033,0.034841,0.035116,0.030581,0.045727,0.048496,0.044126,0.026784,0.059476,0.042612,...,0.028022,0.050159,0.037868,0.058633,0.037590,0.032799,0.035777,0.046241,0.034850,0.042744

In [21]:
f_v4_1.to_csv('/mnt/datadisk2/aglv/aglv/lab_aglv/aglv_factor/Sep/turnstd_agg5min_noavg_21_23_min.csv')